name: CI Backend

on:
  push:
    branches:
      - desarrollo-alejandro
      - main
  pull_request:
    branches:
      - desarrollo-alejandro
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Cambiar según tu versión

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run .NET tests
      run: dotnet test --no-build --verbosity normal

    # 🧪 A partir de acá empieza Newman
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Versión compatible con Newman

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman tests with Newman
      run: newman run Pruebas_Api_Turnero.postman_collection.json
